[package]
name = "scenario_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_toml = { package = "toml", version = "0.8" }
anyhow = "1.0"
cohesix = { path = "../.." }
