# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.6
# Author: Lukas Bower
# Date Modified: 2028-11-08
[package]
name = "sel4-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cty = { version = "0.2", default-features = false }

[features]
panic-handler = []
default = ["panic-handler"]

[build-dependencies]
bindgen = "0.65"

[lib]
crate-type = ["rlib"]
# Allow non-CamelCase seL4 types
allow = ["non_camel_case_types"]

