# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.3
# Author: Lukas Bower
# Date Modified: 2027-12-31
[package]
name = "sel4-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"
cty = "0.2"

[build-dependencies]
bindgen = "0.65"

[lib]
crate-type = ["staticlib", "rlib"]
# Allow non-CamelCase seL4 types
allow = ["non_camel_case_types"]

