# CLASSIFICATION: COMMUNITY
# Filename: cohesix-secure9p/Cargo.toml v0.6
# Author: Lukas Bower
# Date Modified: 2029-09-26
[package]
name = "cohesix-secure9p"
version = "0.2.0"
edition = "2021"
authors = ["Lukas Bower <lukas@example.com>"]
license = "Apache-2.0"


[dependencies]
cohesix-9p = { path = "../cohesix-9p", features = ["posix"] }
ninep = { path = "../../third_party/ninep_portable", default-features = false }
rustls = { version = "0.21", default-features = false }
rustls-pemfile = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
webpki-roots = "0.25"
log = "0.4"
hex = "0.4"
sha2 = "0.10"
subtle = "2"


[features]
default = ["std"]
std = []
tls = []

[dev-dependencies]
rcgen = "0.11"
tempfile = "3"
