# CLASSIFICATION: COMMUNITY
# Filename: cohesix-secure9p/Cargo.toml v0.5
# Author: Lukas Bower
# Date Modified: 2027-09-30
[package]
name = "cohesix-secure9p"
version = "0.2.0"
edition = "2021"
authors = ["Lukas Bower <lukas@example.com>"]
license = "Apache-2.0"


[dependencies]
ninep = { path = "../../third_party/ninep_portable", default-features = false }


[features]
default = ["std"]
std = []
tls = []
