# Author: Lukas Bower
[package]
name = "cohsh"
version = "0.1.0"
edition = "2021"
description = "Cohesix shell prototype using the live NineDoor Secure9P transport"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
cohesix-ticket = { workspace = true }
secure9p-wire = { workspace = true }
nine-door = { path = "../nine-door" }
