# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.6
# Author: Lukas Bower
# Date Modified: 2027-11-05

[package]
name = "cohesix_root"
version = "0.2.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }


[features]
default = []
alloc_only = []

[profile.release]
panic = "abort"
strip = false
lto = false
codegen-units = 1
opt-level = 1
debug = true

[profile.dev]
panic = "abort"
strip = "symbols"
opt-level = 0
debug = false
debug-assertions = false

# Ensures we keep this crate minimal and no_std compatible
[package.metadata]
no_std = true

[[bin]]
name = "cohesix_root"
path = "src/main.rs"
test = false
