# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.4
# Author: Lukas Bower
# Date Modified: 2027-10-19

[package]
name = "cohesix_root"
version = "0.2.0"
edition = "2021"

[dependencies]


[features]
default = []
alloc_only = []

[profile.release]
panic = "abort"
strip = "debuginfo"

[profile.dev]
panic = "abort"
strip = "symbols"

# Ensures we keep this crate minimal and no_std compatible
[package.metadata]
no_std = true

[[bin]]
name = "cohesix_root"
path = "src/main.rs"
test = false
