# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.3
# Author: Lukas Bower
# Date Modified: 2027-08-17

[package]
name = "cohesix_root"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_derive = { version = "1.0" }
curve25519-dalek = { version = "4.1.3", default-features = false }

[features]
default = []
alloc_only = []

[profile.release]
panic = "abort"
strip = "debuginfo"

# Ensures we keep this crate minimal and no_std compatible
[package.metadata]
no_std = true

[[bin]]
name = "cohesix_root"
path = "src/main.rs"
test = false
