# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.2
# Author: Lukas Bower
# Date Modified: 2027-08-15

[package]
name = "cohesix_root"
version = "0.1.0"
edition = "2021"

[dependencies]
cohesix = { path = "../cohesix", default-features = false }
libm = "0.2"

[features]
default = []

[profile.release]
panic = "abort"
strip = "debuginfo"
