# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.2
# Author: Lukas Bower
# Date Modified: 2027-08-16

[package]
name = "cohesix_root"
version = "0.1.0"
edition = "2021"

[dependencies]
cohesix = { path = "../cohesix", default-features = false }
libm = "0.2"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[features]
default = []

[profile.release]
panic = "abort"
strip = "debuginfo"
