# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.10
# Author: Lukas Bower
# Date Modified: 2030-03-09

[package]
name = "cohesix_root"
version = "0.2.0"
edition = "2021"
build = "build.rs"
links = "sel4-root"


[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
sel4-sys-extern-wrapper = { path = "../sel4-sys-extern-wrapper", default-features = false }


[features]
default = []
alloc_only = []
semihosting = []

[build-dependencies]
cc = "1"
bindgen = "0.69"

# Ensures we keep this crate minimal and no_std compatible
[package.metadata]
no_std = true
rustflags = ["-C", "link-arg=-Tkernel.lds"]

[[bin]]
name = "cohesix_root"
path = "src/main.rs"
test = false
