// CLASSIFICATION: COMMUNITY
// Filename: QueenPrimary.yaml v0.3
// Author: Lukas Bower
// Date Modified: 2027-12-01
role: QueenPrimary
max_workers: 8
orchestration:
  strategy: adaptive
services:
  - validator
  - secure9p
  - telemetry
  - cuda
telemetry: verbose
