// CLASSIFICATION: COMMUNITY
// Filename: SimulatorTest.yaml v0.1
// Author: Lukas Bower
// Date Modified: 2025-08-30
telemetry_interval: 10
trace_policy: "/etc/trace/policy.yaml"
validator: false
# Scenario replay path
scenario_dir: "/sim/scenarios"
