// CLASSIFICATION: COMMUNITY
// Filename: WorkerDrone.yaml v0.1
// Author: Lukas Bower
// Date Modified: 2025-08-30
telemetry_interval: 45
trace_policy: "/etc/trace/policy.yaml"
validator: true
# WorkerDrone specific parameters
worker_threads: 4
