# CLASSIFICATION: COMMUNITY
# Filename: config.toml v0.3
# Author: Codex
# Date Modified: 2028-11-06

[build]
target = "cohesix_root/sel4-aarch64.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
[target.aarch64-unknown-none]
rustflags = ["--sysroot=/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"]
