[package]
name = "cohfuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
anyhow = "1.0"
# removed unused cohesix dependency
clap = { version = "4", features = ["derive"] }
