# CLASSIFICATION: COMMUNITY
# Filename: tools/cohfuzz/Cargo.toml v0.1
# Author: Lukas Bower
# Date Modified: 2028-11-26

[package]
name = "cohfuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
cohesix = { path = "../../cohesix" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[features]
default = []
