# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.4
# Author: Lukas Bower
# Date Modified: 2027-11-06

[workspace]
members = [
    "cohesix",
    "cohesix-9p",
    "cohesix-secure9p",
    "cohesix_root",
    "tools/cli",
    "tools/scenario_compiler",
    "tools/cohfuzz"
]
resolver = "2"

[profile.release]
panic = "abort"
strip = false
lto = true
codegen-units = 1
debug = true

[profile.dev]
panic = "abort"
strip = "symbols"
opt-level = "z"
debug = false
debug-assertions = false
