# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.6
# Author: Lukas Bower
# Date Modified: 2027-12-31

[workspace]
members = [
    "cohesix",
    "cohesix-9p",
    "cohesix-secure9p",
    "cohesix_root",
    "tools/cli",
    "tools/scenario_compiler",
    "tools/cohfuzz",
    "sel4-sys"
]
resolver = "2"

[workspace.dependencies]
sel4-sys = { path = "sel4-sys" }

[profile.release]
panic = "abort"
strip = false
lto = true
codegen-units = 1
debug = true

[profile.dev]
panic = "abort"
strip = "symbols"
opt-level = "z"
debug = false
debug-assertions = false
