# CLASSIFICATION: COMMUNITY
# Filename: Cargo.toml v0.3
# Author: Lukas Bower
# Date Modified: 2027-10-19

[workspace]
members = [
    "cohesix",
    "cohesix-9p",
    "cohesix_root"
]

[profile.release]
panic = "abort"
strip = "debuginfo"

[profile.dev]
panic = "abort"
strip = "symbols"
opt-level = "z"
debug = false
debug-assertions = false
